version: "1"
buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
startCommand: "gunicorn my3dshop.wsgi:application"
envVars:
  - key: DEBUG
    value: "False"
  - key: SECRET_KEY
    generateValue: true
services:
  - type: web
    name: my3dshop
    env: python
    plan: free